[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
hime_redist = "3.5.1"
colored = "2.0.0"
wasm-bindgen = "0.2.63"
cinner = "0.1.2"
priede_std = {path = "../lib/priede-std"}

[lib]
name = "interpreter"
path = "src/main.rs"